version: '3.4'

services:
  loginjwt:
    image: loginjwt
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - ./tmp/db/pg:/var/lib/postgresql/data
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./tmp/db/redis:/data
    ports:
      - "6379:6379"

  web:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - loginjwt

   